package comnickdchee.github.a3am.Models;

import android.media.Image;
import android.os.Parcel;
import android.os.Parcelable;

import java.io.Serializable;
import java.security.acl.Owner;
import java.util.ArrayList;


/**
 * @author Tatenda & Zaheen
 */

public class Book implements Parcelable {

    private String ISBN;
    private String title;
    private String author;
    private String image;                   // Stored as URL from firebase storage.
    private String ownerID;
    private User owner;
    private Status status;
    private ArrayList<String> requests = new ArrayList<>();
    private ArrayList<User> requestUsers = new ArrayList<>();
    private User currentBorrower;
    private String bookID;                  // Used for passing through intents.

    /** Used for searching Firebase. */
    public Book() {}

    public Book(String bookID, String ISBN, String title, String author, String Image, String ownerID) {
        this.ISBN = ISBN;
        this.title = title;
        this.author = author;
        this.status = Status.Available;
        this.image = Image;
        this.ownerID = ownerID;
        this.currentBorrower = null;
    }

    public Book(String ISBN, String title, String author) {
        this.ISBN = ISBN;
        this.title = title;
        this.author = author;
        this.status = Status.Available;
        this.currentBorrower = null;
    }

    public Book(String ISBN, String title, String author, String ownerID) {
        this.ISBN = ISBN;
        this.title = title;
        this.author = author;
        this.ownerID = ownerID;
        this.status = Status.Available;
        this.currentBorrower = null;
    }

    public Book(String ISBN, String title, String author, User owner) {
        this.ISBN = ISBN;
        this.title = title;
        this.author = author;
        this.owner = owner;
        this.status = Status.Available;
        this.currentBorrower = null;
    }

    protected Book(Parcel in) {
        ISBN = in.readString();
        title = in.readString();
        author = in.readString();
        bookID = in.readString();
        status = Status.valueOf(in.readString());
        in.readList(requests, null);
        ownerID = in.readString();
    }

    public static final Creator<Book> CREATOR = new Creator<Book>() {
        @Override
        public Book createFromParcel(Parcel in) {
            return new Book(in);
        }

        @Override
        public Book[] newArray(int size) {
            return new Book[size];
        }
    };

    /**
     * Returns a string object
     * @return ISBN uniquely identifies the book
     */
    public String getISBN() {
        return ISBN;
    }

    /** BookID generated by Firebase. */
    public void setBookID(String _bookID) { bookID = _bookID; }

    /** Returns the bookID associated with this book. */
    public String getBookID() { return bookID; }

    /**
     * Takes a string object and sets the ISBN of the book
     * @param ISBN uniquely identifies the book
     */
    public void setISBN(String ISBN) {
        this.ISBN = ISBN;
    }

    /**
     * Returns a string object
     * @return title the title of the book
     */
    public String getTitle() {
        return title;
    }

    /**
     * Takes a string object and sets the title of the book
     * @param title the title of the book
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Returns a string object
     * @return author the author of the book
     */
    public String getAuthor() {
        return author;
    }

    /**
     * takes a string author and sets the author of the book
     * @param author the author of the book
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * Returns an image object
     * @return image coverphoto of the book
     * @see Image
     */
    public String getImage() {
        return image;
    }

    /**
     * Takes in an image object and sets the book cover to it
     * @param image cover photo of the book
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * Takes in a Status object and sets the status
     * @param status status can be avilable, requested, borrowed or accepted
     * @see Status
     */
    public void setStatus(Status status) {this.status = status; }

    /**
     * Returns a status object
     * @return status status can be avilable, requested, borrowed or accepted
     * @see Status
     */
    public Status getStatus() { return status; }

    /**
     * Takes a User object and sets the owner of the book
     * @param owner the owner of the book
     * @see User
     */
    public void setOwner(User owner) { this.owner = owner; }

    /**
     * Returns a User object
     * @return user the owner of the book
     * @see User
     */
    public User getOwner() { return owner; }

    /**
     * Returns a User object
     * @return currentBorrower the current borrower of the book
     * @see User
     */
    public void setOwnerID(String ownerID) { this.ownerID = ownerID; }

    public String getOwnerID() { return ownerID; }

    public User getCurrentBorrower() { return currentBorrower; }

    /** Get each requester in the form of user data. */
    public ArrayList<User> getRequestUsers() {
        return requestUsers;
    }

    /** Setting the users requester list. */
    public void setRequestUsers(ArrayList<User> users) {
        requestUsers = users;
    }

    /**
     * Takes User object; and sets the current borrower of the book
     * @param currentBorrower the current borrower of the book
     * @see User
     */
    public void setCurrentBorrower(User currentBorrower) {this.currentBorrower = currentBorrower; }

    /**
     * Takes a User object and adds it to the list of requests
     * @param uid potential borrower of the book
     * @see User
     */
    public void addRequest(String uid) {requests.add(uid); }

    /**
     * Returns an arrayList of requests placed for the book
     * @return requests
     * @see ArrayList
     */
    public ArrayList<String> getRequests() {
        return requests;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel parcel, int i) {
        parcel.writeString(ISBN);
        parcel.writeString(title);
        parcel.writeString(author);
        parcel.writeString(bookID);
        parcel.writeString(status.name());
        parcel.writeList(requests);
        parcel.writeString(ownerID);
    }

    //public int getBookID() { return bookID; }

}
